from pathlib import Path

BASE_DIR = Path(__file__).parent

DATA_DIR = BASE_DIR / "data"
EXPORT_DIR = BASE_DIR / "exports"

VENTAS_FILE = DATA_DIR / "VENTASXDIA.XLS"
PRODUCTOS_FILE = DATA_DIR / "PRODUCTOS.XLS"
PRODUCTOS_PERIODO_FILE = DATA_DIR / "PRODUCTOSVENDIDOSPERIODO.XLS"

APP_NAME = "Dashboard SOMALU"

COLOR_PRIMARY = "#E63946"
COLOR_SUCCESS = "#2A9D8F"
COLOR_WARNING = "#F4A261"
COLOR_INFO = "#457B9D"